### ISSUE TITLE
for my own image need to train a oneself‘s model ，Is there no general model

### ISSUE THREAD

**Issue by zhanghongyong123456** [gaoalexander/neuphysics#1]

**Comment by gaoalexander** [comment]
Hi @zhanghongyong123456, thanks for your question.  A separate model must be trained for a given set of input images.  If you'd like to use your own custom data, I suggest starting with [custom data preprocessing](https://github.com/gaoalexander/neuphysics/tree/main/preprocess_custom_data).  Once your images have been preprocessed, you can then proceed to train the model on your data.  I hope this helps!
