### ISSUE TITLE
Missing simulation part?

### ISSUE THREAD

**Issue by fishfishson** [gaoalexander/neuphysics#2]
Dear author, 
Appreciate your great work on diff rendering and simulations. However, I cannot find the simulation part in this repo. Do you plan to publish this part in the future? 
Best,

**Comment by gaoalexander** [comment]
Hi @fishfishson you are correct -- the simulation part is not yet included in this repo.  Please stay tuned, as we hope to add it in the near future.  Thanks.

**Comment by fishfishson** [comment]
@gaoalexander Thx for your reply. Looking forward to this part. 
BTW recently DiffCloth from MIT has been released for diff cloth simulations. Is it possible to incorporate it into neuphysics for human video reconstruction?

**Comment by gaoalexander** [comment]
Hi @fishfishson ,

Please see this commit for recently added code for the differentiable physics portion of the pipeline:

https://github.com/gaoalexander/neuphysics/commit/799fe0cdb7e11c4892f38cfd5b8668bc0f64cbe4

As for integrating with DiffCloth, we don't have plans to do so at this time, but in general, combining a geometry reconstruction method for cloth with differentiable cloth simulation seems like an interesting idea.

Best,
Alexander
